/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

/**
 *
 * @author Alexis Tobar R
 */
public class ReservationConfirmationJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReservationConfirmationJDialog.class.getName());

    /**
     * Creates new form ReservationConfirmationJDialog
     */
    public ReservationConfirmationJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        // Ícono
        java.net.URL iconURL = getClass().getResource("/resources/images/check.png");
        if (iconURL != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(iconURL);
            java.awt.Image scaledImage = icon.getImage().getScaledInstance(
                    lblIcon1.getWidth(),
                    lblIcon1.getHeight(),
                    java.awt.Image.SCALE_SMOOTH
            );
            lblIcon1.setIcon(new javax.swing.ImageIcon(scaledImage));
        }

        lblIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon1.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon1.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIcon1 = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        lblSubMessage = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(216, 216, 216));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/check.png"))); // NOI18N
        lblIcon1.setLabelFor(lblIcon1);
        lblIcon1.setText("lblIcon");
        lblIcon1.setMaximumSize(new java.awt.Dimension(64, 64));
        lblIcon1.setMinimumSize(new java.awt.Dimension(64, 64));
        lblIcon1.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel1.add(lblIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 100, 100));

        lblMessage.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(98, 43, 160));
        lblMessage.setText("¡Reserva Exitosa!");
        jPanel1.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 180, -1, -1));

        lblSubMessage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSubMessage.setText("Disfruta la película");
        jPanel1.add(lblSubMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 230, -1, -1));

        btnOk.setBackground(new java.awt.Color(54, 21, 90));
        btnOk.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("Aceptar");
        btnOk.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(54, 21, 90))); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jPanel1.add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ReservationConfirmationJDialog dialog = new ReservationConfirmationJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIcon1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblSubMessage;
    // End of variables declaration//GEN-END:variables

}
